use_frameworks!

target 'LinkedInKit_Example' do
    pod 'LinkedInKit', :path => '../'
    pod 'SDWebImage'

  target 'LinkedInKit_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
